src/main/java/uk/gov/companieshouse/api/strikeoffobjections/config/SpringMongoConfig.java
Copied the config from ptf and manually tested this - _class has been removed.
=> Config to remove class from db data

spec/schema.json
Adding file field to the POST attachment endpoint
=> BI-4302 Updating api spec for POST attachment

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionController.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionMapper.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/response/ObjectionResponseDTO.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java
Jira ticket at: https://companieshouse.atlassian.net/browse/OBJ-125
=> OBJ-125 adding the get objection endpoint

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/common/FormatUtils.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/email/AvroSerializer.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/email/KafkaEmailClient.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/model/EmailContent.java, src/test/java/common/FormatUtilsUnitTest.java, src/test/java/email/AvroSerializerUnitTest.java, src/test/java/email/KafkaEmailClientUnitTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/model/EmailContentTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java, src/test/resources/email/email-send.avsc
Added Kafka client:
Avro serializer does not accept objects including Maps so had to convert the map for email data to a string.
DateFormatter added.
=> OBJ-156 kafka client

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/config/KafkaConfiguration.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/email/KafkaRestClient.java, src/test/java/email/KafkaRestClientUnitTest.java
Beans config, rest client and test for rest client.
=> OBJ-156 Kafka beans configuration

pom.xml, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/email/AvroSerializer.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/email/KafkaEmailClient.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/email/EmailContent.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/ICompanyProfileService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IEmailService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/CompanyProfileService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ERICHeaderParser.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailService.java, src/test/java/email/AvroSerializerUnitTest.java, src/test/java/email/KafkaEmailClientUnitTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/email/EmailContentTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ERICHeaderParserTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java
Added story OBJ-175 to reduce complexity of this pr. For now the companyProfile call just returns dummy data
=> OBJ 157 added email service

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessor.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IEmailService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/CompanyProfileService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessorTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailServiceTest.java
Making ObjectionProcessor send the customer email
=> OBJ-159 Updating ObjectionProcessor to send customer email

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClient.java, src/test/java/chips/ChipsClientTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClientTest.java
Stubbed client and unit test. As the method is void there is not a lot to add.
=> OBJ-242 chips client stub

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClient.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClientTest.java
We are releasing code and the chips work is not ready, disabling CHIPS call for now to allow us to release and test divulge info work
=> Disable Chips call

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClient.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClientTest.java
Switching the call to chips back on for testing
=> OBJ-128 Re-enabling chips call for testing

spec/schema.json
updating schema to replace unused status endpoint with more specific eligibility endpoint.
=> OBJ-323 updating schema with new eligibility endpoint

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionController.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java
Adding logging for the /eligibility endpoint
=> OBJ-386 Adding logging to eligibility endpoint

pom.xml
Adding Jib Maven plugin used to create a Docker image
=> Adding Jib Maven plugin for creating docker image

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsServiceTest.java
Removed feature flag and all code relating to it.
=> OBJ-350 Removed chips contact feature flag

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/client/OracleQueryClient.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/Gaz2RequestedValidator.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/client/OracleQueryClientTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/Gaz2RequestedValidatorTest.java
Added a check for companies with Action code of GAZ1. To check if a GAZ2 has been requested against the company. If it has, the company is ineligible.
=> Add Gaz2 requested validation

spec/schema.json, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/config/ValidationConfig.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/eligibility/EligibilityStatus.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/eligibility/ObjectionEligibility.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/ObjectionStatus.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/AllowedValuesValidationRule.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/DisallowedValuesValidationRule.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/Gaz2RequestedValidator.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/ValidationException.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/ActionCodeValidatorTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/AllowedValuesValidationRuleTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/DisallowedValuesValidationRuleTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/Gaz2RequestedValidatorTest.java
Add new field to ObjectionEligibility offering some description of why the company is eligibile or not.
The Web will read this field when deciding whether to show GAZ1 date or not
=> Added EligibilityStatus field to ObjectionEligibility

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java
Resolving: [BI-7337](https://companieshouse.atlassian.net/browse/BI-7337)
=> Remove not necessary TODO comments flagged by Sonar

spec/schema.json
Added Objector to spec to use for new web screens
=> Added Objector to spec

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/create/ObjectionCreate.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/CreatedBy.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/patch/ObjectionPatch.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/patcher/ObjectionPatcher.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/response/CreatedByResponseDTO.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/CompanyNumberInterceptorIntegrationTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/ObjectionStatusInterceptorIntegrationTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/authorization/UserAuthorizationInterceptorIntegrationTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/authorization/UserAuthorizationInterceptorTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/ObjectionTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/patcher/ObjectionPatcherTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessorTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java
Adding the objector field
Partially resolves: [OBJ-513](https://companieshouse.atlassian.net/browse/OBJ-513)
=> Adding the objector field

spec/schema.json
Resolves: [BI-7663](https://companieshouse.atlassian.net/browse/BI-7663)
=> Updating spec to change objector field to mandatory

pom.xml
Bump httpclient from 4.5.8 to 4.5.13
Part of [BI-8520](https://companieshouse.atlassian.net/browse/BI-8520)
=> Bump httpclient from 4.5.8 to 4.5.13

pom.xml
Updated maven-jib docker plugin to 3.1.4 to fix concourse issues
=> Updated maven-jib version to 3.1.4

src/main/resources/application.properties, terraform/groups/ecs-service/locals.tf
Add a healthcheck path and map to it in terraform
=> Use actuator healthcheck path and correct healthcheck route

terraform/groups/ecs-service/locals.tf
=> fix: Corrected the spelling error

terraform/groups/ecs-service/locals.tf
=> fix: updated the priority value to a unique value

pom.xml
The vulnerability addressed: CVE-2024-22233
CC-1077
=> fix: patched Spring Boot to address new vulnerability

.gitignore, terraform/groups/ecs-service/locals.tf
=> fix: Corrected the port 8080 -> 5009 for the health check

terraform/groups/ecs-service/data.tf, terraform/groups/ecs-service/main.tf
Set up strike off routes on internalapi only
=> Setup strike-off on internal lb only

pom.xml
Remove api-sdk-java unused dependency from pom
I've run the compile, unit and integration tests locally and all are passing.
=> Remove api-sdk-java unused dependency from pom

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/client/OracleQueryClient.java
Adding extra logs to the OracleQueryClient to debug the issue in cidev (to be reverted)
=> Adding extra logs (to be reverted)
