pom.xml
Addresses this warning message at start-up:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/mwestacott/dev/SingleService/strike-off-objections-api/target/strike-off-objections-api-unversioned.jar!/BOOT-INF/lib/structured-logging-1.9.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/mwestacott/dev/SingleService/strike-off-objections-api/target/strike-off-objections-api-unversioned.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
=> BI-3864 Exclude dependencies that were causing an SLF4J warning message

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/common/ApiLogger.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionController.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClient.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClientResponse.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiResponse.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferOperation.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferResponseBuilder.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClientUnitTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java, src/test/resources/input/testMultipart.txt
Borrowed heavily from extensions-api - have refactored out the annonymous calls in the client into their own methods so it is more readable and clearer what the objects returned are. Moreover, updated unit tests to use junit jupiter. Also added headers to the response object in line with the acceptance criteria.
So far only been able to test with unit tests.
=> obj-63-add-attachment-to-api

src/main/resources/application.properties
Setting max upload size to 6mb. File-transfer-api is limited to 4mb so this should give it some headroom and block stupidly large files.
6mb will be set in the config.
=> OBJ-70 Tomcat default upload is 1mb. Setting to 6mb.

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionController.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClient.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClientUnitTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java
Call to the file transfer api to removed the file from s3 will proceeed with deletion from mongo if s3 deletion is sucessful so as to avoid leaving the objection in an inconsistent state.
Added unit tests for the service and file transfer client.
=> OBJ-134 File Transfer Api call for delete

spec/schema.json, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/common/ApiLogger.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionController.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/exception/InvalidObjectionStatusException.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/processor/InvalidObjectionStatusException.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessor.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessorTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java
Adding an initial objection processor that is called when a patch containing status = SUBMITTED is sent in to the api.
=> OBJ-159 initial submit objection processing

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailService.java
Changing the switch to determine jurisdiction for email - default is cardiff
=> OBJ-171 refactoring email jurisdiction switch

spec/schema.json
When create is called and a company is not eligible an HTTP 406 code: NOT_ACEPTABLE is returned. One of 4 status is possible 3 corresponding to the ineligibility codes on OBJ-208 and 1 if no codes are present as described on OBJ-209.
=> OBJ-227 Ineligible http code

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionController.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/ObjectionStatus.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/IObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/ObjectionStatusTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java
Updated service call to return a DTO rather than a string which contains a status as well as an id.
The controller will return an hhtp 400 error and a body ctaining a dto with the objection status in it.
For the response have used a normal body rather than an error body as this takes an error container object and will mean alterations to the agreed schema.
=> OBJ-232 api controller return obj status for eligibility

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/common/LogConstants.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/Objection.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/AllowedValuesValidationRule.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/validation/DisallowedValuesValidationRule.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/ObjectionTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/AllowedValuesValidationRuleTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/validation/DisallowedValuesValidationRuleTest.java
Plugging in the actionCodeValidator into ObjectionService so we can validate the action code when creating a new Objection
Also, the ObjectionService constructor args list had grown too large (Sonar) so had to move them out into fields.
=> OBJ-231 Integrate action code validation into create objection

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/CreatedBy.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/EmailService.java
Jackson uses getters to serialize objects, canShareIdentity is not standard so Jackson didn't know it could use it to serialize the shareIdentity field.
=> OBJ-263 change can to is

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/controller/CreatedByMapper.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/create/ObjectionCreate.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/patch/ObjectionPatch.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/response/CreatedByResponseDTO.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/response/ObjectionResponseDTO.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java
Just updated the two PRs - the created by returned when GET is called for display on the check your answers page was left as it was the thing causing problems with serialization earlier - but if I add a DTO for created by then the var can be reformatted here as well.
=> OBJ-299 annotations to receiver name format correction in the web

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequestTest.java
Made the new attachments mapping null safe and found a neat way of converting the attachments map to a string (also null safe).
Added tests to cover these.
=> OBJ-312 Adding null checks for attachments in ChipsRequest

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequest.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClientTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequestTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsServiceTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java
Added the 4 new fields to the ChipsRequest object:
**attachments** - map with name and url string taken from links with the SELF key
**referenceNumber** - empty string for now to be implemented i OBJ-162
**customerEmai**l
**reason**
=> OBJ-312 include chips contact fields in objectons api client

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/eligibility/ObjectionEligibility.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ObjectionService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java
Changing company eligible check to just use the actionCodeValidator and remove the need for converting to an ObjectionStatus to get the result.
Refactoring calls to actionCodeValidator so we only have to log the action code once
=> OBJ-322 Removing use of ObjectionStatus in company eligible check

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequest.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequestTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsServiceTest.java
Adding new feature flag to allow us to not send the contact data to chips if chips code to handle it is not deployed.
The flag being set to true will mean that nulls get set in the ChipsRequest which has been updated to ignore null fields when converting to json.
=> OBJ-20 Adding feature flag for sending chips contact data

src/test/java/uk/gov/companieshouse/api/strikeoffobjections/controller/ObjectionControllerTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/utils/Utils.java
Fixing Sonar bug in ObjectionControllerTest. Noticed that the mock pluggableResponseEntityFactory were returning dummy objects so I found a way of capturing the input into the mock in order to return it as well (using mockito Answer).
Also added a few not null checks to stop my IDE highlighting possible null pointer issues.
Fixed a few other IDE issues like adding the generic types to some classes.
=> SONAR - Updating attachment tests in ObjectionControllerTest

src/test/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClientUnitTest.java
updating exception testing and removing use of expected exception
Noticed a bit of un-needed code in testNullClientHttpResponseForDownload so trimmed it out
=> SONAR - updating FileTransferApiClientUnitTest for sonar smells

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequest.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsService.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsClientTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/model/chips/ChipsRequestTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/service/impl/ChipsServiceTest.java
https://companieshouse.atlassian.net/browse/OBJ-356
Updated the ChipsRequest model  and service with full name and share identity.
Updated the chips service, request and client unit tests to include the two new fields.
=> obj-356 Updated model to include name and share identity

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/common/ApiLogger.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/common/ApiLoggerTest.java
This will result in correct messages in the TEST and LIVE logs, e.g.
```
{"created":"2020-10-21T14:03:14.555Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"message":"GET /{objectionId} request received","company_number":"05916434","objection_id":"5f903f9e938cb425e88c81f0"}}
{"created":"2020-10-21T14:03:14.602Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"message":"Finished GET /{objectionId} request","company_number":"05916434","objection_id":"5f903f9e938cb425e88c81f0"}}
```
As opposed to output with duplicate messages:
```
{"created":"2020-10-21T14:03:14.555Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"messag …
```
=> OBJ-210 Clone map passed to structured logging to stop duplicate message

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/config/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/CompanyNumberInterceptor.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/ObjectionInterceptor.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/ObjectionStatusInterceptor.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/authorization/AttachmentDownloadAuthorizationInterceptor.java, src/main/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/authorization/UserAuthorizationInterceptor.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/config/InterceptorConfigTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/ObjectionInterceptorTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/ObjectionStatusInterceptorIntegrationTest.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/interceptor/ObjectionStatusInterceptorTest.java
The Objection Status check in ObjectionInterceptor was blocking downloads due to the objection status not being OPEN.
I've extracted the status check into it's own interceptor to give us greater control over how we apply it.
We can now exclude the download path from the status check.
=> OBJ-397 cannot download attachment of processed objection

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessor.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessorTest.java
Moving call to get company profile before sending chips data during processing to prevent half processed cases if company profile api is unavailable.
=> OBJ-408 move company profile call during processing

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/model/entity/Objection.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/processor/ObjectionProcessorTest.java
Removing a reason text check to allow objections with empty reasons to be processed.
=> OBJ-413 Make api accept objections with empty reason text

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClient.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/file/FileTransferApiClientUnitTest.java
Spring monitors calls to external apis.
By constructing the url from a string each time, each call was counted as a seperate call.
Using URI variables allows spring to recognize each call as the same with different paramaters
=> Obj 451 uri variables when calling file transfer

src/main/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsKafkaClient.java, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsKafkaClientTest.java
Logger is unable to convert ChipsRestInterfacesSend into JSON causing the log to not work.
Logging out ChipsRestInterfaceSend.data instead should work
=> Log message data not message

pom.xml
Bump log4j-to-slf4j from 2.15.0 to 2.16.0
Resolves part of [DEBT-1507](https://companieshouse.atlassian.net/browse/DEBT-1507)
=> Bump log4j-to-slf4j from 2.15.0 to 2.16.0

pom.xml
updated companies-house-parent version to have latest build from concourse as part of jenkins to concourse migration 
(https://companieshouse.atlassian.net/browse/CC-53)
=> CC-53 : Updated pom to have latest version of companies-house-parent 

Makefile, pom.xml, suppress.xml
5 libraries were updated to latest to remove the reported vulnerabilities:
* rest-service-common-library
* ch-kafka
* api-sdk-java
* api-sdk-manager-java-library
* kafka-models
Added supressions due to the Sonar plugin not yet having a patched release available
CC-1098
=> Addressed the vulnerabilities present in the current version

terraform/groups/ecs-service/data.tf, terraform/groups/ecs-service/main.tf
Add third load balancer route path to strike-off-objections-api:
https://github.com/companieshouse/strike-off-objections-web/blob/master/src/modules/sdk/objections/service.ts#L17
=> Add third lb for internalapi, used by web service

README.md, pom.xml, src/test/java/uk/gov/companieshouse/api/strikeoffobjections/chips/ChipsKafkaClientTest.java, suppress.xml
* Updated a number of libraries to the latest versions to remove some vulnerabilities
* Due to downgrading kaka clients new CVE supressions were added
doc: README.md
* Added three mandatory fields top the table
* Recorded the fact that kafka-clients needs to be explicitly added as a dependency
CC-1212
=> fix: Downgraded kafka-clients to `2.3.1` due to compatibility issues

pom.xml
Rolling back kafka-client to previous version.
This was updated to version 3.7.1 in this PR: https://github.com/companieshouse/strike-off-objections-api/pull/167
We started getting this issue in the dev environments after bumping up the version. 
On debugging further we came across this PR which exclusively sets the kafka-client version to an older one due to compatibility issues. 
https://github.com/companieshouse/strike-off-objections-api/pull/158
=> Rollback to previous version of kafka-client
